"""Module for handling namespaces."""

from kgraphpy.namespaces import CGMES_CIM, CGMES_EU
from rdflib import Graph, URIRef
from rdflib.namespace import NamespaceManager
from typing import Any
import logging

logger = logging.getLogger("primary")


def align_cgmes_namespaces(graph: Graph, context: dict) -> None:
    """Align the namespaces in the context with those in the graph if they match CGMES namespaces.

    This allows the same context to be used for graphs with the CGMES exception namespaces (loaded from CIMXML files),
    as well as for graphs with the standard CIM and EU namespaces.

    CGMES namespaces:
        CGMES_CIM (prefix 'cim'): http://iec.ch/TC57/CIM100#
        CGMES_EU (prefix 'eu'): http://iec.ch/TC57/CIM100-EuropeanExtension/1/0#
    
    Parameters:
        graph (Graph): The RDFLib Graph containing the data and namespaces.
        context (dict): The JSON-LD context dictionary to be aligned. Expected to have a "@context" key with a dictionary value.
    """
    if not isinstance(context, dict) or not isinstance(context.get("@context"), dict):
        logger.error(f"Context has unexpected structure. No alignment performed.")
        return
    
    namespaces: NamespaceManager = graph.namespace_manager
    if namespaces.store.namespace("cim") == URIRef(CGMES_CIM):
        context["@context"]["cim"] = CGMES_CIM

    if namespaces.store.namespace("eu") == URIRef(CGMES_EU):
        context["@context"]["eu"] = CGMES_EU
    

def _get_ns_map(graph: Graph) -> dict[str, str]:
    """Helper function to get a mapping of namespace URIs to prefixes from an RDFLib Graph.
    
    Parameters:
        graph (Graph): The RDFLib Graph from which to extract namespaces.

    Returns:
        dict: A dictionary mapping namespace URIs (as strings) to their prefixes.
    """
    return {str(ns): prefix for prefix, ns in graph.namespace_manager.namespaces()}


def compare_namespaces(graphs: dict[str, Graph | None]) -> list[dict]:
    """Compare the namespaces used in multiple RDFLib Graphs and generate a report.

    Example input:
    graphs = {
        "data": Graph,
        "rdfs": Graph (optional),
        "shacl": Graph
    }

    Parameters:
        graphs (dict): A dictionary mapping graph names to RDFLib Graph instances.

    Returns:        
        list: A list of dictionaries, each containing:
                - "uri": The namespace URI being compared.
                - "presence": A dictionary mapping graph names to the prefix used for the namespace, or None if not present.
                - "missing": A list of graph names where the namespace is missing.
    """

    ns_maps: dict[str, dict[str, str]] = {name: _get_ns_map(g) for name, g in graphs.items() if g is not None}

    all_uris: set[str] = set().union(*(m.keys() for m in ns_maps.values()))

    report: list[dict] = []

    for uri in sorted(all_uris):
        row: dict[str, Any] = {
            "uri": uri,
            "presence": {},
            "missing": []
        }

        for name, ns_map in ns_maps.items():
            if uri in ns_map:
                row["presence"][name] = ns_map[uri]
            else:
                row["presence"][name] = None
                row["missing"].append(name)

        report.append(row)

    return report


def all_namespaces_match(report: list[dict]) -> bool:
	"""Check if all namespaces match across graphs based on the report generated by compare_namespaces.
	
	Parameters:
		report (list): The report generated by compare_namespaces, which is a list of dictionaries containing namespace comparison results.

	Returns:
		bool: True if all namespaces match (i.e., no missing namespaces in any graph), False otherwise.
	"""
	return all(len(row["missing"]) == 0 for row in report)


def format_namespace_matrix(report: list[dict], graph_names: list[str]) -> str:
	"""Format the namespace comparison report into a readable matrix format for display.
	
	Parameters:
		report (list): The report generated by kgverifypy.namespaces.compare_namespaces, which is a list of dictionaries containing namespace comparison results.
		graph_names (list): A list of graph names corresponding to the graphs compared in the report, used for labeling the columns in the matrix.

	Returns:
		str: A formatted string representing the namespace comparison matrix.
	"""
	max_uri_len: int = max(len(row["uri"]) for row in report) if report else 0
	col_width: int = 10

	lines: list[str] = []

	header: str = "Namespace".ljust(max_uri_len) + " | " + " | ".join(name.upper().center(col_width) for name in graph_names)
	lines.append(header)
	lines.append("-" * len(header))

	for row in report:
		if row["missing"]:
			uri_part: str = row["uri"].ljust(max_uri_len)

			cols: list[str] = []
			for name in graph_names:
				prefix = row["presence"].get(name)
				if prefix:
					cols.append(f"✔ {prefix}".center(col_width))
				else:
					cols.append("✘".center(col_width))

			line: str = uri_part + " | " + " | ".join(cols)
			lines.append(line)	

	return "\n".join(lines)



if __name__ == "__main__":
    print("Namespace module for KGVerifyPy.")